# This workflow will build a Java project with Maven

name: Build and publish quickstart to quay

on:
  push:
    branches: [ issue-82 ]
    ## Other guides 
    paths:
    - "code-examples/quarkus/kafka-quickstart"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and run Unit tests
      working-directory: code-examples/quarkus/kafka-quickstart
      run: mvn install --no-transfer-progress \
          -Dquarkus.container-image.username=${{ secrets.quay_robotaccount }}  \
          -Dquarkus.container-image.name=kafka-quickstart
          -Dquarkus.container-image.password=${{ secrets.quay_robottoken }} \ 
          -Dquarkus.container-image.build=true -Dquarkus.container-image.tag=${{ steps.version-number.outputs.version }} \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.group=rhoas 
  
            
      

