# This workflow will build a quickstart image to be used in the guide and CI/CD

name: Build and publish quickstarts to quay

on:
  push:
    tags:
      - 'v*'
    #branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt' # See 'Supported distributions' for available options
    - name: Build and publish to quay
      working-directory: code-examples/quarkus-kafka-quickstart
      run: ./mvnw clean package --file pom.xml --no-transfer-progress 
                      -Dquarkus.container-image.build=true 
                      -Dquarkus.container-image.push=true 
                      -Dquarkus.container-image.username="${{ secrets.quay_robotaccount }}" 
                      -Dquarkus.container-image.password="${{ secrets.quay_robottoken }}"
                      -Dquarkus.container-image.tag=latest
                      -Dquarkus.container-image.image=quay.io/rhoas/rhoas-quarkus-kafka-quickstart
